# Generated by Django 4.0.2 on 2022-02-16 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_post_dislikes_alter_comment_date_alter_post_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='top',
            field=models.BooleanField(default=False),
        ),
    ]
