# Generated by Django 4.0.2 on 2022-02-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_author_user_alter_comment_date_alter_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
