# Generated by Django 4.0.2 on 2022-02-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_post_dislikes_alter_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='images/photo_2020-11-07_20-26-31.jpg', upload_to='images/'),
        ),
    ]
