# Generated by Django 4.0.2 on 2022-02-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_post_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
